// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: pb/data/data.proto

package data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Data_SaveBlock_FullMethodName      = "/data.Data/SaveBlock"
	Data_DownloadObject_FullMethodName = "/data.Data/DownloadObject"
)

// DataClient is the client API for Data service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataClient interface {
	SaveBlock(ctx context.Context, opts ...grpc.CallOption) (Data_SaveBlockClient, error)
	DownloadObject(ctx context.Context, in *DownloadObjectReq, opts ...grpc.CallOption) (Data_DownloadObjectClient, error)
}

type dataClient struct {
	cc grpc.ClientConnInterface
}

func NewDataClient(cc grpc.ClientConnInterface) DataClient {
	return &dataClient{cc}
}

func (c *dataClient) SaveBlock(ctx context.Context, opts ...grpc.CallOption) (Data_SaveBlockClient, error) {
	stream, err := c.cc.NewStream(ctx, &Data_ServiceDesc.Streams[0], Data_SaveBlock_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &dataSaveBlockClient{stream}
	return x, nil
}

type Data_SaveBlockClient interface {
	Send(*SaveBlockReq) error
	CloseAndRecv() (*SaveBlockResp, error)
	grpc.ClientStream
}

type dataSaveBlockClient struct {
	grpc.ClientStream
}

func (x *dataSaveBlockClient) Send(m *SaveBlockReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataSaveBlockClient) CloseAndRecv() (*SaveBlockResp, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SaveBlockResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataClient) DownloadObject(ctx context.Context, in *DownloadObjectReq, opts ...grpc.CallOption) (Data_DownloadObjectClient, error) {
	stream, err := c.cc.NewStream(ctx, &Data_ServiceDesc.Streams[1], Data_DownloadObject_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &dataDownloadObjectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Data_DownloadObjectClient interface {
	Recv() (*DownloadObjectResp, error)
	grpc.ClientStream
}

type dataDownloadObjectClient struct {
	grpc.ClientStream
}

func (x *dataDownloadObjectClient) Recv() (*DownloadObjectResp, error) {
	m := new(DownloadObjectResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataServer is the server API for Data service.
// All implementations must embed UnimplementedDataServer
// for forward compatibility
type DataServer interface {
	SaveBlock(Data_SaveBlockServer) error
	DownloadObject(*DownloadObjectReq, Data_DownloadObjectServer) error
	mustEmbedUnimplementedDataServer()
}

// UnimplementedDataServer must be embedded to have forward compatible implementations.
type UnimplementedDataServer struct {
}

func (UnimplementedDataServer) SaveBlock(Data_SaveBlockServer) error {
	return status.Errorf(codes.Unimplemented, "method SaveBlock not implemented")
}
func (UnimplementedDataServer) DownloadObject(*DownloadObjectReq, Data_DownloadObjectServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadObject not implemented")
}
func (UnimplementedDataServer) mustEmbedUnimplementedDataServer() {}

// UnsafeDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServer will
// result in compilation errors.
type UnsafeDataServer interface {
	mustEmbedUnimplementedDataServer()
}

func RegisterDataServer(s grpc.ServiceRegistrar, srv DataServer) {
	s.RegisterService(&Data_ServiceDesc, srv)
}

func _Data_SaveBlock_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataServer).SaveBlock(&dataSaveBlockServer{stream})
}

type Data_SaveBlockServer interface {
	SendAndClose(*SaveBlockResp) error
	Recv() (*SaveBlockReq, error)
	grpc.ServerStream
}

type dataSaveBlockServer struct {
	grpc.ServerStream
}

func (x *dataSaveBlockServer) SendAndClose(m *SaveBlockResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataSaveBlockServer) Recv() (*SaveBlockReq, error) {
	m := new(SaveBlockReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Data_DownloadObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadObjectReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServer).DownloadObject(m, &dataDownloadObjectServer{stream})
}

type Data_DownloadObjectServer interface {
	Send(*DownloadObjectResp) error
	grpc.ServerStream
}

type dataDownloadObjectServer struct {
	grpc.ServerStream
}

func (x *dataDownloadObjectServer) Send(m *DownloadObjectResp) error {
	return x.ServerStream.SendMsg(m)
}

// Data_ServiceDesc is the grpc.ServiceDesc for Data service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Data_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.Data",
	HandlerType: (*DataServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SaveBlock",
			Handler:       _Data_SaveBlock_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadObject",
			Handler:       _Data_DownloadObject_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/data/data.proto",
}
