// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: pb/data/data.proto

package data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Data_SaveBlock_FullMethodName     = "/data.Data/SaveBlock"
	Data_DownloadBlock_FullMethodName = "/data.Data/DownloadBlock"
)

// DataClient is the client API for Data service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataClient interface {
	SaveBlock(ctx context.Context, in *SaveBlockReq, opts ...grpc.CallOption) (*SaveBlockResp, error)
	DownloadBlock(ctx context.Context, in *DownloadBlockReq, opts ...grpc.CallOption) (*DownloadBlockResp, error)
}

type dataClient struct {
	cc grpc.ClientConnInterface
}

func NewDataClient(cc grpc.ClientConnInterface) DataClient {
	return &dataClient{cc}
}

func (c *dataClient) SaveBlock(ctx context.Context, in *SaveBlockReq, opts ...grpc.CallOption) (*SaveBlockResp, error) {
	out := new(SaveBlockResp)
	err := c.cc.Invoke(ctx, Data_SaveBlock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) DownloadBlock(ctx context.Context, in *DownloadBlockReq, opts ...grpc.CallOption) (*DownloadBlockResp, error) {
	out := new(DownloadBlockResp)
	err := c.cc.Invoke(ctx, Data_DownloadBlock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServer is the server API for Data service.
// All implementations must embed UnimplementedDataServer
// for forward compatibility
type DataServer interface {
	SaveBlock(context.Context, *SaveBlockReq) (*SaveBlockResp, error)
	DownloadBlock(context.Context, *DownloadBlockReq) (*DownloadBlockResp, error)
	mustEmbedUnimplementedDataServer()
}

// UnimplementedDataServer must be embedded to have forward compatible implementations.
type UnimplementedDataServer struct {
}

func (UnimplementedDataServer) SaveBlock(context.Context, *SaveBlockReq) (*SaveBlockResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveBlock not implemented")
}
func (UnimplementedDataServer) DownloadBlock(context.Context, *DownloadBlockReq) (*DownloadBlockResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadBlock not implemented")
}
func (UnimplementedDataServer) mustEmbedUnimplementedDataServer() {}

// UnsafeDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServer will
// result in compilation errors.
type UnsafeDataServer interface {
	mustEmbedUnimplementedDataServer()
}

func RegisterDataServer(s grpc.ServiceRegistrar, srv DataServer) {
	s.RegisterService(&Data_ServiceDesc, srv)
}

func _Data_SaveBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveBlockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).SaveBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Data_SaveBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).SaveBlock(ctx, req.(*SaveBlockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_DownloadBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadBlockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).DownloadBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Data_DownloadBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).DownloadBlock(ctx, req.(*DownloadBlockReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Data_ServiceDesc is the grpc.ServiceDesc for Data service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Data_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.Data",
	HandlerType: (*DataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveBlock",
			Handler:    _Data_SaveBlock_Handler,
		},
		{
			MethodName: "DownloadBlock",
			Handler:    _Data_DownloadBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/data/data.proto",
}
