// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: pb/meta/meta.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMetaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket   string `protobuf:"bytes,1,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Key      string `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	ObjectID uint64 `protobuf:"varint,3,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
}

func (x *CreateMetaReq) Reset() {
	*x = CreateMetaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_meta_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMetaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMetaReq) ProtoMessage() {}

func (x *CreateMetaReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMetaReq.ProtoReflect.Descriptor instead.
func (*CreateMetaReq) Descriptor() ([]byte, []int) {
	return file_pb_meta_meta_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMetaReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *CreateMetaReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateMetaReq) GetObjectID() uint64 {
	if x != nil {
		return x.ObjectID
	}
	return 0
}

type CreateMetaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *CreateMetaResp) Reset() {
	*x = CreateMetaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_meta_meta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMetaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMetaResp) ProtoMessage() {}

func (x *CreateMetaResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_meta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMetaResp.ProtoReflect.Descriptor instead.
func (*CreateMetaResp) Descriptor() ([]byte, []int) {
	return file_pb_meta_meta_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMetaResp) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateMetaResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ExistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *ExistReq) Reset() {
	*x = ExistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_meta_meta_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistReq) ProtoMessage() {}

func (x *ExistReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_meta_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistReq.ProtoReflect.Descriptor instead.
func (*ExistReq) Descriptor() ([]byte, []int) {
	return file_pb_meta_meta_proto_rawDescGZIP(), []int{2}
}

func (x *ExistReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ExistReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ExistResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ExistResp) Reset() {
	*x = ExistResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_meta_meta_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistResp) ProtoMessage() {}

func (x *ExistResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_meta_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistResp.ProtoReflect.Descriptor instead.
func (*ExistResp) Descriptor() ([]byte, []int) {
	return file_pb_meta_meta_proto_rawDescGZIP(), []int{3}
}

func (x *ExistResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type GetMetaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *GetMetaReq) Reset() {
	*x = GetMetaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_meta_meta_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaReq) ProtoMessage() {}

func (x *GetMetaReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_meta_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaReq.ProtoReflect.Descriptor instead.
func (*GetMetaReq) Descriptor() ([]byte, []int) {
	return file_pb_meta_meta_proto_rawDescGZIP(), []int{4}
}

func (x *GetMetaReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GetMetaReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetMetaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectID uint64 `protobuf:"varint,1,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	Code     uint32 `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg      string `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *GetMetaResp) Reset() {
	*x = GetMetaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_meta_meta_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaResp) ProtoMessage() {}

func (x *GetMetaResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_meta_meta_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaResp.ProtoReflect.Descriptor instead.
func (*GetMetaResp) Descriptor() ([]byte, []int) {
	return file_pb_meta_meta_proto_rawDescGZIP(), []int{5}
}

func (x *GetMetaResp) GetObjectID() uint64 {
	if x != nil {
		return x.ObjectID
	}
	return 0
}

func (x *GetMetaResp) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetMetaResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_meta_meta_proto protoreflect.FileDescriptor

var file_pb_meta_meta_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x55, 0x0a, 0x0d, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x42,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x44, 0x22, 0x36, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x34, 0x0a, 0x08, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22,
	0x23, 0x0a, 0x09, 0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x36, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x22, 0x4f, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d,
	0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x32, 0x99, 0x01,
	0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x13, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x28, 0x0a, 0x05, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x10, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x6d, 0x65,
	0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_meta_meta_proto_rawDescOnce sync.Once
	file_pb_meta_meta_proto_rawDescData = file_pb_meta_meta_proto_rawDesc
)

func file_pb_meta_meta_proto_rawDescGZIP() []byte {
	file_pb_meta_meta_proto_rawDescOnce.Do(func() {
		file_pb_meta_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_meta_meta_proto_rawDescData)
	})
	return file_pb_meta_meta_proto_rawDescData
}

var file_pb_meta_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_meta_meta_proto_goTypes = []interface{}{
	(*CreateMetaReq)(nil),  // 0: meta.CreateMetaReq
	(*CreateMetaResp)(nil), // 1: meta.CreateMetaResp
	(*ExistReq)(nil),       // 2: meta.ExistReq
	(*ExistResp)(nil),      // 3: meta.ExistResp
	(*GetMetaReq)(nil),     // 4: meta.GetMetaReq
	(*GetMetaResp)(nil),    // 5: meta.GetMetaResp
}
var file_pb_meta_meta_proto_depIdxs = []int32{
	0, // 0: meta.Meta.CreateMeta:input_type -> meta.CreateMetaReq
	2, // 1: meta.Meta.Exist:input_type -> meta.ExistReq
	4, // 2: meta.Meta.GetMeta:input_type -> meta.GetMetaReq
	1, // 3: meta.Meta.CreateMeta:output_type -> meta.CreateMetaResp
	3, // 4: meta.Meta.Exist:output_type -> meta.ExistResp
	5, // 5: meta.Meta.GetMeta:output_type -> meta.GetMetaResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_meta_meta_proto_init() }
func file_pb_meta_meta_proto_init() {
	if File_pb_meta_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_meta_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMetaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_meta_meta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMetaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_meta_meta_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_meta_meta_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_meta_meta_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_meta_meta_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_meta_meta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_meta_meta_proto_goTypes,
		DependencyIndexes: file_pb_meta_meta_proto_depIdxs,
		MessageInfos:      file_pb_meta_meta_proto_msgTypes,
	}.Build()
	File_pb_meta_meta_proto = out.File
	file_pb_meta_meta_proto_rawDesc = nil
	file_pb_meta_meta_proto_goTypes = nil
	file_pb_meta_meta_proto_depIdxs = nil
}
